name: Push image to DockerHub
on:
  push:
    branches:
      - develop
      - RB-*
      - fastapi

jobs:
   Dockerhub:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Publish Docker to Docker Hub
         uses: elgohr/Publish-Docker-Github-Action@master
         with:
           name: restbase/base_image
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           dockerfile: Dockerfile
           workdir: restbase/base_image/
           tags: "fastapi"
